### PR TITLE
[fix]: update libs and remove aqua from examples

### PR DESCRIPTION
**Pull request by ErmachenkoBoris**
Updated requirments.txt and change import  QuantumInstance from aqua to utils

### CODE REVIEW

**Review by GroenteLepel — APPROVED** [review]

**Comment by GroenteLepel** [comment]
Qiskit Aqua is till in the tests, so the checks fail trying to merge this.

**Comment by ErmachenkoBoris** [comment]
> Qiskit Aqua is till in the tests, so the checks fail trying to merge this.

Ok, I see, I will fix

**Comment by ErmachenkoBoris** [comment]
@GroenteLepel Hi, will you approve?

**Comment by GroenteLepel** [comment]
Sorry for the late reply. This is strange, because the error that is being generated is an `aqua.AquaError()`. If it works on your side than I’ll just merge this and accept that my tests are just not written for this kind of migration.

**Comment by ErmachenkoBoris** [comment]
My bad, I find an error, sorry, will return with new fix

**Comment by ErmachenkoBoris** [comment]
@GroenteLepel Hello,
I tried to get rid of qiskit aqua completely:
1) abstract classes QuantumAlgorithm and _QSVM_ABC - I didn't find them in the new version of qiskit - I just copied them from qiskit.aqua and created special files for them
2) the get_subsystems_counts function - also not found in the latest version of qiskit. Solution: created a utils file and copied get_subsystems_counts from qiskit.aqua
3) AquaError -> ValueError

**Comment by GroenteLepel** [comment]
Thank you for this, very good.

**Comment by ErmachenkoBoris** [comment]
Thank you for your library and for your excellent scientific work - I am doing my master's work in this field and it helps me a lot

**Pull request merged**
